### ISSUE TITLE
1.4.4 PyPI/GitHub release (go through the checklist first)

### ISSUE THREAD

**Issue by bobleesj** [diffpy/diffpy.pdffit2#101]
### PyPI/GitHub rc-release preparation checklist:

- [x] All PRs/issues attached to the release are merged.
- [x] All the badges on the README are passing.
- [x] License information is verified as correct. If you are unsure, please comment below.
- [x] Locally rendered documentation contains all appropriate pages, including API references (check no modules are
  missing), tutorials, and other human written text is up-to-date with any changes in the code.
- [x] Installation instructions in the README, documentation and on the website (e.g., diffpy.org) are updated.
- [x] Successfully run any tutorial examples or do functional testing with the latest Python version.
- [x] Grammar and writing quality are checked (no typos).

*Creating this release to check-off items for now.

### PyPI/GitHub  full-release preparation checklist:
- [ ] Create a new conda environment and install the rc from pypi (`pip install <package-name>=??`)
- [ ] License information at Pypi is verified as correct.
- [ ] Docs deployed successfully to `<package-name>.github.io`
- [ ] Successfully run all tests, tutorial examples or do functional testing

Please let  @sbillinge know that all checks are done and package is ready for full release.

### conda-forge release preparation checklist:

- [ ] Ensure that the full release has appeared on Pypi successfully
- [ ] New package dependencies listed in `conda.txt` and `test.txt` are added to `meta.yaml` in the feedstock.
- [ ] Close any open issues on the feedstock.  Reach out to @bobleesj if you have questions
- [ ] let @sbillinge and @bobleesj when this is ready

### Post-release checklist

- [ ]  Run tutorial examples and conduct functional testing using the installation guide in the README. Attach screenshots/results as comments.
- [ ]  Documentation (README, tutorials, API references, and websites) is deployed without broken links or missing figures.

**Comment by bobleesj** [comment]
Notes: 

Dec 4, 2024 - Thursday
- `pdffit2 rc` `.whl` files have been deployed to https://pypi.org/project/diffpy.pdffit2/1.4.4rc6/#files
- Before full release, we are testing Py3.12 supporting`pdfgui` with this `pdffit_rc`.

**Comment by bobleesj** [comment]
Will close this since @Tieqiong is spearheading pdffit2 and pdfgui
